/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */



module Decoder2 (
    output out_0,
    output out_1,
    output out_2,
    output out_3,
    input [1:0] sel
);
    assign out_0 = (sel == 2'h0)? 1'b1 : 1'b0;
    assign out_1 = (sel == 2'h1)? 1'b1 : 1'b0;
    assign out_2 = (sel == 2'h2)? 1'b1 : 1'b0;
    assign out_3 = (sel == 2'h3)? 1'b1 : 1'b0;
endmodule




module DispM (
  input [1:0] scan,
  input [15:0] HEXS,
  input [3:0] point,
  input [3:0] LES,
  output [3:0] AN,
  output [7:0] SEGMENT
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire [3:0] s14;
  wire [3:0] s15;
  wire [3:0] s16;
  wire [3:0] s17;
  wire [3:0] s18;
  wire s19;
  wire s20;
  wire s21;
  wire s22;
  MUX421 MUX421_i0 (
    .I( point ),
    .S( scan ),
    .O( s5 )
  );
  MUX421 MUX421_i1 (
    .I( LES ),
    .S( scan ),
    .O( s4 )
  );
  Decoder2 Decoder2_i2 (
    .sel( scan ),
    .out_0( s19 ),
    .out_1( s20 ),
    .out_2( s21 ),
    .out_3( s22 )
  );
  assign s14 = HEXS[3:0];
  assign s15 = HEXS[7:4];
  assign s16 = HEXS[11:8];
  assign s17 = HEXS[15:12];
  MUX424 MUX424_i3 (
    .S( scan ),
    .I0( s14 ),
    .I1( s15 ),
    .I2( s16 ),
    .I3( s17 ),
    .F( s18 )
  );
  assign AN[0] = ~ s19;
  assign AN[1] = ~ s20;
  assign AN[2] = ~ s21;
  assign AN[3] = ~ s22;
  assign s3 = s18[0];
  assign s2 = s18[1];
  assign s1 = s18[2];
  assign s0 = s18[3];
  G7segement G7segement_i4 (
    .D3( s0 ),
    .D2( s1 ),
    .D1( s2 ),
    .D0( s3 ),
    .LE( s4 ),
    .point( s5 ),
    .a( s6 ),
    .b( s7 ),
    .d( s8 ),
    .c( s9 ),
    .e( s10 ),
    .f( s11 ),
    .g( s12 ),
    .p( s13 )
  );
  assign SEGMENT[0] = s6;
  assign SEGMENT[1] = s7;
  assign SEGMENT[2] = s9;
  assign SEGMENT[3] = s8;
  assign SEGMENT[4] = s10;
  assign SEGMENT[5] = s11;
  assign SEGMENT[6] = s12;
  assign SEGMENT[7] = s13;
endmodule
