/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module G7segement (
  input D3,
  input D2,
  input D1,
  input D0,
  input LE,
  input point,
  output a,
  output b,
  output d,
  output c,
  output e,
  output f,
  output g,
  output p
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  assign s0 = ~ D3;
  assign s1 = ~ D2;
  assign s2 = ~ D1;
  assign s3 = ~ D0;
  assign a = (((D3 & D2 & s2 & D0) | (D3 & s1 & D1 & D0) | (s0 & D2 & s2 & s3) | (s0 & s1 & s2 & D0)) | LE);
  assign b = (((s3 & D2 & D3) | (s3 & D1 & D2) | (D0 & D1 & D3) | (D0 & s2 & D2 & s0)) | LE);
  assign c = (((D1 & D2 & D3) | (s3 & D2 & D3) | (s3 & D1 & s1 & s0)) | LE);
  assign d = (((D0 & D1 & D2) | (s3 & D1 & s1 & D3) | (s3 & s2 & D2 & s0) | (D0 & s2 & s1 & s0)) | LE);
  assign e = (((D0 & s0) | (s2 & D2 & s0) | (D0 & s2 & s1)) | LE);
  assign f = (((D0 & D1 & s0) | (D1 & s1 & s0) | (D0 & s1 & s0) | (D0 & s2 & D2 & D3)) | LE);
  assign g = (((s3 & s2 & D2 & D3) | (D0 & D1 & D2 & s0) | (s2 & s1 & s0)) | LE);
  assign p = point;
endmodule
